import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import '@fontsource-variable/newsreader/opsz.css'
import '@fontsource-variable/newsreader/opsz-italic.css'
import '@fontsource-variable/geist/index.css'
import '@fontsource-variable/geist-mono/index.css'
import 'katex/dist/katex.min.css'
import './styles/tokens.css'
import './styles/base.css'
import './styles/layout.css'
import './styles/prose.css'
import './styles/components.css'
import './styles/widgets.css'
import './styles/blocks.css'
import './styles/l01.css'
import './styles/l02.css'
import './styles/l03.css'
import './styles/l04.css'
import './styles/l05.css'
import './styles/l06.css'
import './styles/l07.css'
import './styles/l08.css'
import './styles/l09.css'
import './styles/l10.css'
import './styles/l11.css'
import './styles/l12.css'
import './styles/l13.css'
import './styles/l14.css'
import './styles/l15.css'
import './styles/l16.css'
import './styles/l17.css'
import './styles/l18.css'
import './styles/l19.css'
import './styles/glass.css'
import App from './App.tsx'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
