/**
 * Glossario: definizioni brevi, tratte dagli appunti.
 * `section` è il titolo della sezione in cui il termine è spiegato (serve per il link).
 */
export type GlossaryEntry = {
  id: string
  term: string
  en?: string
  def: string
  lesson: string
  section: string
}

export const glossary: GlossaryEntry[] = [
  // ------------------------------------------------------------------ 01
  {
    id: 'machine-learning',
    term: 'Machine Learning',
    en: 'apprendimento automatico',
    def: 'Apprendimento automatico, da parte di un sistema, a partire dall’**esperienza** (un insieme di esempi), finalizzato a risolvere un compito computazionale.',
    lesson: '01',
    section: 'Che cos’è il Machine Learning',
  },
  {
    id: 'prodotto-scalare',
    term: 'Prodotto scalare',
    en: 'inner / dot product',
    def: '$\\mathbf{a}\\cdot\\mathbf{b}=\\sum_i a_i b_i=|\\mathbf{a}||\\mathbf{b}|\\cos\\theta$. Misura quanto due vettori puntano nella stessa direzione: massimo se paralleli, nullo se ortogonali, negativo se opposti.',
    lesson: '01',
    section: 'Prodotto scalare e norme',
  },
  {
    id: 'norma',
    term: 'Norma euclidea',
    def: '$\\|\\mathbf{x}\\|_2=\\sqrt{\\mathbf{x}^T\\mathbf{x}}=\\sqrt{\\sum_i x_i^2}$: la lunghezza del vettore, cioè la sua distanza dall’origine.',
    lesson: '01',
    section: 'Prodotto scalare e norme',
  },
  {
    id: 'tensore',
    term: 'Tensore',
    def: 'Nella visione semplificata del ML, un array multidimensionale di numeri su una griglia regolare con un numero variabile di assi (es. $X_{i,j,k}$).',
    lesson: '01',
    section: 'Prodotto scalare e norme',
  },
  {
    id: 'gradiente',
    term: 'Gradiente',
    def: 'Il vettore delle derivate parziali $\\nabla f=(\\partial f/\\partial x_1,\\dots,\\partial f/\\partial x_n)$. Punta nella direzione di **massima crescita** di $f$; la sua norma dice quanto è ripida la pendenza.',
    lesson: '01',
    section: 'Derivate parziali e gradiente',
  },
  {
    id: 'discesa-del-gradiente',
    term: 'Discesa del gradiente',
    en: 'gradient descent',
    def: 'Idea alla base dell’addestramento: muoversi nella direzione $-\\nabla f$, quella in cui la funzione di errore **decresce** più rapidamente.',
    lesson: '01',
    section: 'Derivate parziali e gradiente',
  },
  {
    id: 'punto-stazionario',
    term: 'Punto stazionario',
    def: 'Punto in cui il gradiente è nullo. Può essere un minimo locale, un massimo locale o un punto di sella: il gradiente nullo da solo non basta a dirlo.',
    lesson: '01',
    section: 'Derivate parziali e gradiente',
  },
  {
    id: 'gaussiana',
    term: 'Gaussiana',
    en: 'distribuzione normale',
    def: 'Densità $f(x)=\\frac{1}{\\sigma\\sqrt{2\\pi}}e^{-(x-\\mu)^2/(2\\sigma^2)}$ con media $\\mu$ e varianza $\\sigma^2$. Con $\\mu=0,\\ \\sigma^2=1$ è la normale standard.',
    lesson: '01',
    section: 'Densità di probabilità: la gaussiana',
  },

  // ------------------------------------------------------------------ 03
  {
    id: 'pattern',
    term: 'Pattern',
    en: 'esempio, istanza, campione',
    def: 'Una riga $\\mathbf{x}$ del dataset. $\\mathbf{x}_p$ è il $p$-esimo pattern; il dataset ne contiene $l$.',
    lesson: '03',
    section: 'Dati',
  },
  {
    id: 'feature',
    term: 'Feature',
    en: 'attributo, componente',
    def: 'Una delle $n$ proprietà che descrivono ogni esempio: $x_i$ è la $i$-esima feature di $\\mathbf{x}$.',
    lesson: '03',
    section: 'Dati',
  },
  {
    id: 'one-hot',
    term: 'Codifica one-hot',
    en: '1-of-k',
    def: 'Ogni simbolo diventa un vettore con un solo 1, es. $A=(1,0,0)$, $B=(0,1,0)$, $C=(0,0,1)$: tutti i simboli risultano **equidistanti**.',
    lesson: '03',
    section: 'Codifica delle variabili categoriche',
  },
  {
    id: 'rumore',
    term: 'Rumore',
    en: 'noise',
    def: 'Fattori esterni aggiunti al segnale informativo, dovuti alla casualità delle misure e non alla legge sottostante (es. rumore gaussiano).',
    lesson: '03',
    section: 'Rumore, outlier e feature selection',
  },
  {
    id: 'outlier',
    term: 'Outlier',
    def: 'Valore insolito, incoerente con la maggior parte delle osservazioni. Si rimuove in pre-elaborazione o si usano metodi **robusti**.',
    lesson: '03',
    section: 'Rumore, outlier e feature selection',
  },
  {
    id: 'feature-selection',
    term: 'Feature selection',
    def: 'Selezione di un piccolo numero di feature informative, per una rappresentazione ottimale dell’input.',
    lesson: '03',
    section: 'Rumore, outlier e feature selection',
  },
  {
    id: 'supervisionato',
    term: 'Apprendimento supervisionato',
    def: 'Si apprende da esempi **etichettati** $\\langle\\mathbf{x},d\\rangle$, con il target $d$ fornito da un “insegnante”, per trovare un’ipotesi $h$ che approssimi $f$ e generalizzi.',
    lesson: '03',
    section: 'Apprendimento supervisionato',
  },
  {
    id: 'non-supervisionato',
    term: 'Apprendimento non supervisionato',
    def: 'Nessun insegnante: solo dati non etichettati $\\langle\\mathbf{x}\\rangle$. Obiettivi tipici: clustering, riduzione di dimensionalità, stima della densità.',
    lesson: '03',
    section: 'Apprendimento non supervisionato',
  },
  {
    id: 'classificazione',
    term: 'Classificazione',
    def: 'Task supervisionato con target **categorico**: $f(\\mathbf{x})\\in\\{1,\\dots,K\\}$. Geometricamente, divide lo spazio degli input in regioni di decisione.',
    lesson: '03',
    section: 'Classificazione',
  },
  {
    id: 'concept-learning',
    term: 'Concept learning',
    def: 'Classificazione binaria: imparare una funzione booleana (vero/falso, $0/1$, $-1/+1$).',
    lesson: '03',
    section: 'Classificazione',
  },
  {
    id: 'ltu',
    term: 'Linear Threshold Unit',
    en: 'LTU',
    def: 'Classificatore $h(\\mathbf{x})=\\operatorname{sign}(\\mathbf{w}^T\\mathbf{x}+w_0)$: separa lo spazio degli input con un iperpiano.',
    lesson: '03',
    section: 'Classificazione',
  },
  {
    id: 'regressione',
    term: 'Regressione',
    def: 'Task supervisionato con target **numerico**: stima di una funzione a valori reali a partire da campioni rumorosi $(\\mathbf{x}, f(\\mathbf{x})+\\text{rumore})$.',
    lesson: '03',
    section: 'Regressione',
  },
  {
    id: 'clustering',
    term: 'Clustering',
    def: 'Partizione dei dati in sottoinsiemi di elementi “simili”, ognuno rappresentato da un centroide (prototipo).',
    lesson: '03',
    section: 'Apprendimento non supervisionato',
  },
  {
    id: 'self-supervised',
    term: 'Self-supervised learning',
    def: 'Apprendimento supervisionato con etichette generate automaticamente dalla struttura dei dati (es. predire la parola successiva). È alla base del pre-addestramento degli LLM.',
    lesson: '03',
    section: 'Altri paradigmi',
  },
  {
    id: 'reinforcement-learning',
    term: 'Reinforcement learning',
    def: 'Apprendimento con un “critico” che dice giusto/sbagliato: si impara una **politica** su come agire; ogni azione ha un effetto sull’ambiente, che risponde con un feedback.',
    lesson: '03',
    section: 'Altri paradigmi',
  },
  {
    id: 'funzione-target',
    term: 'Funzione target',
    def: 'La vera funzione $f$, sconosciuta, che si vuole approssimare. È nota solo nei punti degli esempi.',
    lesson: '03',
    section: 'Modello',
  },
  {
    id: 'ipotesi',
    term: 'Ipotesi',
    def: 'Una funzione $h$ proposta, che si ritiene simile alla funzione target $f$.',
    lesson: '03',
    section: 'Modello',
  },
  {
    id: 'spazio-delle-ipotesi',
    term: 'Spazio delle ipotesi',
    def: 'L’insieme $H$ di tutte le ipotesi che l’algoritmo di apprendimento può, in linea di principio, produrre. È il modello a definirlo.',
    lesson: '03',
    section: 'Modello',
  },
  {
    id: 'no-free-lunch',
    term: 'No Free Lunch',
    def: 'Non esiste un metodo di apprendimento universalmente migliore: se vince su alcuni problemi, deve perdere su altri.',
    lesson: '03',
    section: 'Modello',
  },
  {
    id: 'bias-induttivo',
    term: 'Bias induttivo',
    def: 'Le assunzioni sulla natura della funzione target — vincoli sul modello (**language bias**) o preferenze nella ricerca (**search bias**). Senza bias non c’è generalizzazione.',
    lesson: '03',
    section: 'Il bias induttivo',
  },
  {
    id: 'language-bias',
    term: 'Language bias',
    def: 'Bias induttivo dato da vincoli sullo spazio delle ipotesi $H$: si restringe ciò che il modello può esprimere.',
    lesson: '03',
    section: 'Il bias induttivo',
  },
  {
    id: 'search-bias',
    term: 'Search bias',
    def: 'Bias induttivo affidato alla strategia di ricerca dell’algoritmo, che privilegia certe soluzioni rispetto ad altre. È quello preferito nel ML moderno.',
    lesson: '03',
    section: 'Language bias o search bias?',
  },
  {
    id: 'version-space',
    term: 'Version space',
    def: 'Il sottoinsieme $VS_{H,TR}$ delle ipotesi di $H$ **consistenti** con tutti gli esempi di training, cioè con $h(\\mathbf{x})=d(\\mathbf{x})$ su ogni esempio.',
    lesson: '03',
    section: 'Restringere lo spazio: le regole congiuntive',
  },
  {
    id: 'lookup-table',
    term: 'Lookup table',
    def: 'Un *rote learner*: memorizza gli esempi e classifica solo input già visti (altrimenti “nessuna risposta”). Nessun bias, nessuna generalizzazione.',
    lesson: '03',
    section: 'Imparare funzioni booleane: un problema mal posto',
  },
  {
    id: 'unbiased-learner',
    term: 'Unbiased learner',
    def: 'Learner con $H=\\mathcal{P}(X)$, capace di esprimere ogni concetto. Classifica senza ambiguità solo gli esempi di training: non può generalizzare.',
    lesson: '03',
    section: 'L’unbiased learner',
  },
  {
    id: 'loss',
    term: 'Funzione di loss',
    def: '$L(h_\\mathbf{w}(\\mathbf{x}),d)$: misura, sul singolo pattern, la distanza tra l’uscita del modello e il target. Un valore alto indica un’approssimazione scarsa.',
    lesson: '03',
    section: 'Task e funzioni di loss',
  },
  {
    id: 'errore',
    term: 'Errore (rischio, loss)',
    def: 'Valore atteso della loss, ad esempio la media sugli $l$ esempi: $E(\\mathbf{w})=\\frac1l\\sum_p L(h_\\mathbf{w}(\\mathbf{x}_p),d_p)$. È la funzione obiettivo del training.',
    lesson: '03',
    section: 'Task e funzioni di loss',
  },
  {
    id: 'mse',
    term: 'Mean Squared Error',
    en: 'MSE',
    def: 'Media degli errori quadratici $(d_p-h_\\mathbf{w}(\\mathbf{x}_p))^2$ sul dataset: la loss tipica della regressione.',
    lesson: '03',
    section: 'Regressione: errore quadratico',
  },
  {
    id: 'generalizzazione',
    term: 'Generalizzazione',
    def: 'Quanto accuratamente il modello predice su **dati nuovi**, mai visti. È il concetto fondamentale del corso; si stima con un test set tenuto da parte.',
    lesson: '03',
    section: 'Generalizzazione e validazione',
  },

  // ------------------------------------------------------------------ 04
  {
    id: 'overfitting',
    term: 'Overfitting',
    def: 'Il learner restituisce $h$ quando esiste $h’\\in H$ con errore di training maggiore ($E’>E$) ma errore vero minore ($R’<R$): il modello si adatta troppo ai dati, rumore compreso.',
    lesson: '04',
    section: 'Generalizzazione e overfitting',
  },
  {
    id: 'underfitting',
    term: 'Underfitting',
    def: 'Il modello è troppo semplice rispetto alla funzione target e non ne coglie l’andamento: errore alto già sui dati di training.',
    lesson: '04',
    section: 'Effetto del grado del polinomio',
  },
  {
    id: 'erms',
    term: 'Errore RMS',
    en: 'Root-Mean-Square',
    def: '$E_{RMS}=\\sqrt{2E(\\mathbf{w}^*)/l}$: dividere per $l$ rende confrontabili dataset di dimensione diversa, la radice riporta l’errore sulla scala del target.',
    lesson: '04',
    section: 'Errore di training e di test al variare di $M$',
  },
  {
    id: 'regolarizzazione',
    term: 'Regolarizzazione',
    def: 'Penalizzare i pesi grandi per controllare la complessità del modello. Nasce dall’osservazione che l’overfitting produce coefficienti enormi.',
    lesson: '04',
    section: 'Errore di training e di test al variare di $M$',
  },
  {
    id: 'rischio',
    term: 'Rischio',
    en: 'errore vero',
    def: '$R=\\int L(d,h(\\mathbf{x}))\\,dP(\\mathbf{x},d)$: l’errore atteso su **tutti** i dati possibili, secondo la distribuzione (sconosciuta) $P$.',
    lesson: '04',
    section: 'Il setting formale (semplificato)',
  },
  {
    id: 'rischio-empirico',
    term: 'Rischio empirico',
    def: '$R_{emp}=\\frac1l\\sum_p (d_p-h(\\mathbf{x}_p))^2$: l’errore calcolato sul training set, l’unico che possiamo misurare direttamente.',
    lesson: '04',
    section: 'Il setting formale (semplificato)',
  },
  {
    id: 'erm',
    term: 'ERM',
    en: 'Empirical Risk Minimization',
    def: 'Principio induttivo: si scelgono i parametri che minimizzano il rischio empirico $R_{emp}$, sperando che approssimi il rischio vero $R$.',
    lesson: '04',
    section: 'Il setting formale (semplificato)',
  },
  {
    id: 'vc-dimension',
    term: 'VC-dimension',
    def: 'Misura della complessità di $H$, cioè della sua flessibilità nell’adattarsi ai dati (per modelli lineari o polinomi è legata al numero di parametri).',
    lesson: '04',
    section: 'VC-dimension e bound sul rischio',
  },
  {
    id: 'vc-confidence',
    term: 'VC-confidence',
    def: 'Il termine $\\varepsilon$ del VC-bound $R\\le R_{emp}+\\varepsilon$: cresce con la VC-dimension, decresce con il numero di dati $l$.',
    lesson: '04',
    section: 'VC-dimension e bound sul rischio',
  },
  {
    id: 'srm',
    term: 'Structural Risk Minimization',
    en: 'SRM',
    def: 'Minimizzare il bound $R_{emp}+\\varepsilon$ invece del solo $R_{emp}$: un compromesso tra complessità (VC-dim) e accuratezza sul training.',
    lesson: '04',
    section: 'VC-dimension e bound sul rischio',
  },
  {
    id: 'model-selection',
    term: 'Model selection',
    def: 'Stimare l’errore di generalizzazione di **diversi modelli** (e iperparametri) per scegliere il migliore. Restituisce un modello.',
    lesson: '04',
    section: 'I due obiettivi della validazione',
  },
  {
    id: 'model-assessment',
    term: 'Model assessment',
    def: 'Scelto il modello finale, stimarne l’errore di predizione su **nuovi dati di test**. Restituisce una stima.',
    lesson: '04',
    section: 'I due obiettivi della validazione',
  },
  {
    id: 'iperparametri',
    term: 'Iperparametri',
    def: 'Le scelte che definiscono il modello, come il grado $M$ del polinomio. Non sono i pesi trovati dal training: si fissano con la model selection.',
    lesson: '04',
    section: 'I due obiettivi della validazione',
  },
  {
    id: 'hold-out',
    term: 'Hold-out',
    def: 'Partizione del dataset in tre insiemi **disgiunti**: training set (TR), validation set (VL) e test set (TS).',
    lesson: '04',
    section: 'Hold-out',
  },
  {
    id: 'training-set',
    term: 'Training set',
    en: 'TR',
    def: 'Gli esempi usati per eseguire l’algoritmo di apprendimento.',
    lesson: '04',
    section: 'Hold-out',
  },
  {
    id: 'validation-set',
    term: 'Validation set',
    en: 'VL, selection set',
    def: 'Gli esempi usati per scegliere il modello migliore, ad esempio per regolare gli iperparametri.',
    lesson: '04',
    section: 'Hold-out',
  },
  {
    id: 'test-set',
    term: 'Test set',
    en: 'TS',
    def: 'Gli esempi usati **solo** per la model assessment: mai per scegliere o regolare $h$.',
    lesson: '04',
    section: 'Hold-out',
  },
  {
    id: 'k-fold',
    term: 'K-fold cross-validation',
    def: 'Si divide il dataset in $k$ parti disgiunte; a turno ognuna fa da validazione e le altre da training; si combinano i $k$ risultati.',
    lesson: '04',
    section: 'K-fold cross-validation (anticipazione)',
  },
  {
    id: 'matrice-di-confusione',
    term: 'Matrice di confusione',
    def: 'Tabella che incrocia classe reale e classe predetta: veri positivi (TP), falsi negativi (FN), falsi positivi (FP), veri negativi (TN).',
    lesson: '04',
    section: 'Matrice di confusione',
  },
  {
    id: 'accuratezza',
    term: 'Accuratezza',
    def: '$(TP+TN)/\\text{totale}$: la percentuale di pattern classificati correttamente. Con dati sbilanciati può essere fuorviante.',
    lesson: '04',
    section: 'Matrice di confusione',
  },
  {
    id: 'sensibilita',
    term: 'Sensibilità',
    en: 'recall, TP rate',
    def: '$TP/(TP+FN)$: quanti dei positivi veri vengono riconosciuti.',
    lesson: '04',
    section: 'Matrice di confusione',
  },
  {
    id: 'specificita',
    term: 'Specificità',
    en: 'TN rate',
    def: '$TN/(FP+TN)=1-FPR$: quanti dei negativi veri vengono riconosciuti.',
    lesson: '04',
    section: 'Matrice di confusione',
  },
  {
    id: 'precisione',
    term: 'Precisione',
    def: '$TP/(TP+FP)$: quanti dei predetti positivi sono davvero positivi.',
    lesson: '04',
    section: 'Matrice di confusione',
  },
  {
    id: 'curva-roc',
    term: 'Curva ROC',
    def: 'Il TP rate in funzione dell’FP rate al variare della soglia di decisione. La diagonale è il classificatore casuale; l’area sottesa (AUC) vale 1 per quello ideale.',
    lesson: '04',
    section: 'Curva ROC',
  },
  // ------------------------------------------------------------------ 05
  {
    id: 'lms',
    term: 'Least Mean Squares',
    en: 'LMS, minimi quadrati',
    def: 'Si scelgono i pesi che minimizzano la somma (o la media) dei quadrati dei residui $\\sum_p (y_p - h_\\mathbf{w}(\\mathbf{x}_p))^2$. È l’approccio standard ai sistemi sovradeterminati.',
    lesson: '05',
    section: 'Apprendimento tramite Least Mean Squares',
  },
  {
    id: 'bias-intercetta',
    term: 'Bias (intercetta)',
    en: 'intercept, offset',
    def: 'Il peso $w_0$ del modello lineare, detto anche soglia o offset. Con la componente costante $x_0 = 1$ entra nel prodotto scalare $\\mathbf{x}^T\\mathbf{w}$.',
    lesson: '05',
    section: 'Notazione per input multidimensionali',
  },
  {
    id: 'confine-di-decisione',
    term: 'Confine di decisione',
    en: 'decision boundary',
    def: 'L’iperpiano $\\mathbf{w}^T\\mathbf{x} + w_0 = 0$ che separa la regione classificata positiva da quella negativa; in due dimensioni è una retta. $\\mathbf{w}$ gli è ortogonale.',
    lesson: '05',
    section: 'Iperpiani e regioni di decisione',
  },
  {
    id: 'equazioni-normali',
    term: 'Equazioni normali',
    def: '$(X^TX)\\,\\mathbf{w} = X^T\\mathbf{y}$: si ottengono imponendo il gradiente nullo dell’errore quadratico. Se $X^TX$ è non singolare la soluzione è $\\mathbf{w} = (X^TX)^{-1}X^T\\mathbf{y}$.',
    lesson: '05',
    section: 'Approccio diretto: le equazioni normali',
  },
  {
    id: 'pseudoinversa',
    term: 'Pseudoinversa di Moore-Penrose',
    def: 'Generalizza l’inversa a matrici non invertibili: $\\mathbf{w} = X^+\\mathbf{y}$ è la soluzione ai minimi quadrati a norma minima. Si calcola con la SVD: $X^+ = V\\Sigma^+U^T$.',
    lesson: '05',
    section: 'Approccio diretto: le equazioni normali',
  },
  {
    id: 'learning-rate',
    term: 'Learning rate',
    en: 'step size',
    def: 'Il coefficiente $\\eta$ della regola $\\mathbf{w}_{new} = \\mathbf{w} + \\eta\\,\\Delta\\mathbf{w}$: regola la lunghezza del passo, cioè il compromesso tra velocità e stabilità della discesa.',
    lesson: '05',
    section: 'La regola di apprendimento (delta rule)',
  },
  {
    id: 'epoca',
    term: 'Epoca',
    en: 'epoch',
    def: 'Un passaggio completo su tutto il training set. Nella versione batch i pesi si aggiornano una volta per epoca.',
    lesson: '05',
    section: 'Batch e on-line',
  },
  {
    id: 'online-sgd',
    term: 'Discesa on-line (stocastica)',
    en: 'SGD',
    def: 'Variante della discesa del gradiente in cui i pesi si aggiornano dopo **ogni** pattern, con il gradiente del singolo esempio. Fa progressi a ogni esempio ma richiede un $\\eta$ più piccolo.',
    lesson: '05',
    section: 'Batch e on-line',
  },
  {
    id: 'delta-rule',
    term: 'Delta rule',
    en: 'regola di Widrow-Hoff',
    def: '$\\Delta w_j \\propto \\sum_p \\delta_p\\, x_{p,j}$ con $\\delta_p = y_p - \\mathbf{x}_p^T\\mathbf{w}$: ogni peso cambia in proporzione all’errore e al suo input. È una regola di correzione dell’errore.',
    lesson: '05',
    section: 'Interpretazione: una regola di correzione dell’errore',
  },
  {
    id: 'separabilita-lineare',
    term: 'Separabilità lineare',
    def: 'Due insiemi di punti sono linearmente separabili se un iperpiano (una retta nel piano) li separa completamente. Lo XOR su quattro punti non lo è.',
    lesson: '05',
    section: 'Classificazione: separabilità lineare',
  },
  {
    id: 'basis-expansion',
    term: 'Linear basis expansion',
    en: 'LBE',
    def: '$h_\\mathbf{w}(\\mathbf{x}) = \\sum_k w_k\\,\\phi_k(\\mathbf{x})$ con trasformazioni $\\phi_k$ fissate dell’input: modello non lineare in $\\mathbf{x}$ ma **lineare nei parametri**, addestrabile con gli stessi minimi quadrati.',
    lesson: '05',
    section: 'Linear Basis Expansion (LBE)',
  },
  {
    id: 'curse-of-dimensionality',
    term: 'Maledizione della dimensionalità',
    en: 'curse of dimensionality',
    def: 'Il volume dello spazio cresce così in fretta con la dimensione che i dati disponibili diventano sparsi: gli intorni non sono più locali e servono moltissimi dati.',
    lesson: '05',
    section: 'La maledizione della dimensionalità',
  },
  {
    id: 'ridge',
    term: 'Ridge regression',
    en: 'regolarizzazione di Tikhonov',
    def: 'Si aggiunge alla loss la penalità $\\lambda\\|\\mathbf{w}\\|^2$, che favorisce pesi piccoli e modelli più lisci. Soluzione diretta: $\\mathbf{w} = (X^TX + \\lambda I)^{-1}X^T\\mathbf{y}$.',
    lesson: '05',
    section: 'Ridge regression (regolarizzazione di Tikhonov)',
  },
  {
    id: 'weight-decay',
    term: 'Weight decay',
    def: 'La regola a gradiente della ridge regression, $\\mathbf{w}_{new} = \\mathbf{w} + \\eta\\,\\Delta\\mathbf{w} - 2\\lambda\\mathbf{w}$: a ogni passo ogni peso si riduce di una frazione del suo valore.',
    lesson: '05',
    section: 'Soluzione',
  },
  {
    id: 'lasso',
    term: 'Lasso',
    def: 'Regolarizzazione con la norma $L_1$ ($\\lambda\\sum_j |w_j|$): tende a portare alcuni pesi esattamente a zero, una forma di feature selection. La loss non è differenziabile in zero.',
    lesson: '05',
    section: 'Altre tecniche di regolarizzazione',
  },
  {
    id: 'eager-lazy',
    term: 'Apprendimento eager e lazy',
    def: '**Eager**: si costruisce un’ipotesi esplicita dai dati di training (es. il modello lineare). **Lazy**: si memorizzano i dati e si costruisce un’ipotesi ad hoc solo quando arriva un punto di test (es. il K-NN).',
    lesson: '05',
    section: 'Apprendimento eager e lazy',
  },
  {
    id: 'k-nn',
    term: 'K-nearest neighbors',
    en: 'K-NN',
    def: 'Classifica un punto con il voto a maggioranza (o la media, per la regressione) dei $k$ esempi di training più vicini secondo una distanza $d$. Nessun modello da addestrare: è un metodo lazy e locale.',
    lesson: '05',
    section: 'K-nearest neighbors',
  },
  {
    id: 'voronoi',
    term: 'Diagramma di Voronoi',
    def: 'Partizione del piano in celle, una per pattern: ogni cella contiene i punti più vicini a quel pattern che a qualsiasi altro. Il 1-NN assegna a ogni cella l’etichetta del suo pattern.',
    lesson: '05',
    section: 'K-nearest neighbors',
  },
  {
    id: 'bayes',
    term: 'Classificatore ottimo di Bayes',
    en: 'Bayes rate',
    def: '$h(\\mathbf{x}) = \\arg\\max_v P(v \\mid \\mathbf{x})$, calcolabile se si conosce la densità dei dati. Il suo errore (Bayes rate) è il minimo raggiungibile.',
    lesson: '05',
    section: 'Il classificatore ottimo di Bayes',
  },
  // ------------------------------------------------------------------ 06
  {
    id: 'connessionismo',
    term: 'Connessionismo',
    def: 'La «filosofia» delle reti neurali: comportamenti complessi che **emergono** dall’interazione di molte unità computazionali semplici interconnesse.',
    lesson: '06',
    section: 'Le reti neurali come strumento di ML',
  },
  {
    id: 'hebb',
    term: 'Apprendimento hebbiano',
    en: 'Hebb, 1949',
    def: 'Una sinapsi si rafforza quando gli input del neurone (e gli output correlati) si ripetono: i pesi si avvicinano agli input.',
    lesson: '06',
    section: 'L’ispirazione biologica',
  },
  {
    id: 'unita',
    term: 'Unità (neurone artificiale)',
    def: 'Calcola l’input netto $net_i = \\sum_j w_{ij}x_j$ (bias compreso) e l’uscita $o_i = f(net_i)$. $w_{ij}$ è il peso della connessione da $j$ verso $i$.',
    lesson: '06',
    section: 'Il neurone artificiale',
  },
  {
    id: 'funzione-di-attivazione',
    term: 'Funzione di attivazione',
    def: 'La funzione $f$ che l’unità applica all’input netto: lineare (identità), a soglia (Perceptron), sigmoidale (logistica, tanh), ReLU…',
    lesson: '06',
    section: 'Il neurone artificiale',
  },
  {
    id: 'perceptron',
    term: 'Perceptron',
    en: 'Rosenblatt, 1957–1960',
    def: 'Unità a soglia $\\operatorname{sign}(\\mathbf{w}^T\\mathbf{x})$ con il suo algoritmo di apprendimento: corregge i pesi, $\\mathbf{w} \\leftarrow \\mathbf{w} + \\eta d\\mathbf{x}$, solo sui pattern classificati male.',
    lesson: '06',
    section: 'Il Perceptron',
  },
  {
    id: 'convergenza-perceptron',
    term: 'Teorema di convergenza del Perceptron',
    def: 'Se il problema è linearmente separabile, l’algoritmo del Perceptron trova un classificatore perfetto in un numero finito di passi, al più $\\beta\\|\\mathbf{w}^*\\|^2/\\alpha^2$ errori.',
    lesson: '06',
    section: 'Il teorema di convergenza del Perceptron',
  },
  {
    id: 'adaline',
    term: 'Adaline',
    en: 'Adaptive Linear Neuron',
    def: 'Approccio di Widrow e Hoff: durante il training l’unità è lineare e si usa l’LMS (diretto o a gradiente). È quello che si generalizza agli MLP.',
    lesson: '06',
    section: 'Apprendimento per una singola unità',
  },
  {
    id: 'sigmoide',
    term: 'Sigmoide logistica',
    def: '$f_\\sigma(x) = 1/(1 + e^{-ax})$, valori in $[0, 1]$: una versione liscia e differenziabile della soglia. La derivata (con $a = 1$) è $f_\\sigma(1 - f_\\sigma)$.',
    lesson: '06',
    section: 'Funzioni di attivazione sigmoidali',
  },
  {
    id: 'tanh',
    term: 'Tangente iperbolica',
    def: 'La versione simmetrica della sigmoide: $2f_\\sigma(x) - 1 = \\tanh(ax/2)$, valori in $[-1, +1]$. Derivata (con $a = 1$): $1 - \\tanh^2(x)$.',
    lesson: '06',
    section: 'Funzioni di attivazione sigmoidali',
  },
  {
    id: 'relu',
    term: 'ReLU',
    en: 'Rectified Linear Unit',
    def: '$f(x) = \\max(0, x)$: la scelta predefinita nei modelli profondi. La sua approssimazione liscia è la softplus $\\ln(1 + e^x)$.',
    lesson: '06',
    section: 'Altre funzioni di attivazione',
  },
  {
    id: 'mlp',
    term: 'Multi-Layer Perceptron',
    en: 'MLP',
    def: 'Rete di unità organizzate in strati (input, uno o più nascosti, uscita), vista anche come funzione annidata $h(\\mathbf{x}) = f_k(\\sum_j w_{kj} f_j(\\sum_i w_{ji}x_i))$.',
    lesson: '06',
    section: 'Le reti neurali: il Multi-Layer Perceptron',
  },
  {
    id: 'strato-nascosto',
    term: 'Strato nascosto',
    en: 'hidden layer',
    def: 'Strato di unità tra input e uscita: produce una ri-rappresentazione interna degli input (feature di alto livello) che rende più facile il compito dello strato di uscita.',
    lesson: '06',
    section: 'Lo strato nascosto come rappresentazione',
  },
  {
    id: 'feedforward',
    term: 'Rete feedforward',
    def: 'Rete con un’unica direzione input → uscita: il pattern si propaga strato dopo strato fino a $h(\\mathbf{x})$. Le reti ricorrenti aggiungono cicli di feedback.',
    lesson: '06',
    section: 'Architettura e processing feedforward',
  },
  {
    id: 'approssimazione-universale',
    term: 'Approssimazione universale',
    en: 'Cybenko 1989, Hornik et al.',
    def: 'Un MLP con un solo strato nascosto (logistico) e uscita lineare approssima arbitrariamente bene ogni funzione continua su un ipercubo, con abbastanza unità nascoste. È un teorema di esistenza.',
    lesson: '06',
    section: 'L’approssimazione universale',
  },
  {
    id: 'credit-assignment',
    term: 'Credit assignment',
    def: 'Il problema di attribuire alle unità nascoste la loro «responsabilità» nell’errore: per loro non si conosce l’uscita desiderata, quindi il segnale d’errore non è misurabile direttamente.',
    lesson: '06',
    section: 'Il problema del credit assignment',
  },
  {
    id: 'loading-problem',
    term: 'Loading problem',
    def: 'Data una rete e un insieme di esempi, esiste un insieme di pesi consistente con gli esempi? È NP-completo (Judd, 1990).',
    lesson: '06',
    section: 'Il loading problem',
  },
  {
    id: 'backpropagation',
    term: 'Backpropagation',
    def: 'L’algoritmo che estende la discesa del gradiente agli MLP calcolando un delta per ogni unità, anche nascosta; usa solo quantità locali ed è $O(\\#W)$.',
    lesson: '06',
    section: 'L’idea chiave: estendere la discesa del gradiente',
  },
  // ------------------------------------------------------------------ 07
  {
    id: 'regola-della-catena',
    term: 'Regola della catena',
    en: 'chain rule',
    def: '$\\frac{\\partial f}{\\partial x} = \\frac{\\partial f}{\\partial g}\\cdot\\frac{\\partial g}{\\partial x}$: la derivata di una funzione composta si scompone in derivate più semplici. È lo strumento di tutta la backpropagation.',
    lesson: '07',
    section: 'Strumenti di calcolo differenziale',
  },
  {
    id: 'regola-delta-generalizzata',
    term: 'Regola delta generalizzata',
    en: 'Generalized Delta Rule',
    def: 'La delta rule estesa a tutte le unità di una rete: $\\Delta w_{tu} = \\eta\\,\\delta_t\\,o_u$, con il delta delle unità nascoste ottenuto propagando all’indietro quello delle uscite.',
    lesson: '07',
    section: 'Il problema',
  },
  {
    id: 'delta-unita',
    term: 'Delta di un’unità',
    def: '$\\delta_t = -\\partial E_p/\\partial net_t$. Per un’uscita $\\delta_k = (d_k - o_k)f\'_k(net_k)$; per un’unità nascosta $\\delta_j = (\\sum_k \\delta_k w_{kj}) f\'_j(net_j)$.',
    lesson: '07',
    section: 'Il gradiente per un peso generico',
  },
  {
    id: 'fattorizzazione-delta',
    term: 'Fattorizzazione dei delta',
    def: 'Ogni $\\delta_t$ si calcola una sola volta e si riusa per tutti i pesi dell’unità: il costo della backpropagation è proporzionale al numero di pesi, non al suo quadrato.',
    lesson: '07',
    section: 'Proprietà e interpretazione',
  },
  // ------------------------------------------------------------------ 08
  {
    id: 'mini-batch',
    term: 'Mini-batch',
    def: 'Si sommano i gradienti di $mb$ pattern ($1 < mb < l$) prima di aggiornare i pesi, e si ripete finché l’epoca è finita. Compromesso tra on-line e batch, adatto alla memoria della GPU.',
    lesson: '08',
    section: 'Mini-batch',
  },
  {
    id: 'shuffling',
    term: 'Shuffling',
    def: 'Presentare i pattern in ordine casuale diverso a ogni epoca (on-line e mini-batch), per evitare derive sistematiche della discesa.',
    lesson: '08',
    section: 'On-line, batch e mini-batch',
  },
  {
    id: 'momentum',
    term: 'Momentum',
    en: 'heavy ball',
    def: '$\\Delta\\mathbf{w}_{new} = -\\eta\\,\\partial E/\\partial\\mathbf{w} + \\alpha\\,\\Delta\\mathbf{w}_{old}$: a ogni passo si aggiunge una frazione dello spostamento precedente. Accelera nei plateau e smorza le oscillazioni.',
    lesson: '08',
    section: 'Momentum (!)',
  },
  {
    id: 'early-stopping',
    term: 'Early stopping',
    def: 'Fermare l’addestramento quando l’errore su un validation set comincia a salire (con una certa *patience*): poiché la complessità effettiva della rete cresce durante il training, fermarsi prima la limita.',
    lesson: '08',
    section: 'Come nasce l’overfitting in una rete',
  },
  {
    id: 'cascade-correlation',
    term: 'Cascade Correlation',
    en: 'Fahlman e Lebiere, 1990',
    def: 'Algoritmo costruttivo che apprende pesi e numero di unità: aggiunge una unità alla volta, addestrata a massimizzare la correlazione con l’errore residuo, e ne congela i pesi in ingresso.',
    lesson: '08',
    section: 'Cascade Correlation',
  },
  {
    id: 'softmax',
    term: 'Softmax',
    def: '$o_k = e^{net_k}/\\sum_j e^{net_j}$: uscite positive che sommano a 1, interpretabili come probabilità delle classi.',
    lesson: '08',
    section: 'Input e output',
  },
  {
    id: 'cross-entropy',
    term: 'Cross-entropy',
    def: 'Loss alternativa all’errore quadratico per la classificazione (stima di massima verosimiglianza): per un’unità $-\\sum_i \\{d_i\\log out(\\mathbf{x}_i) + (1-d_i)\\log(1 - out(\\mathbf{x}_i))\\}$.',
    lesson: '08',
    section: 'Input e output',
  },
  {
    id: 'standardizzazione',
    term: 'Standardizzazione',
    def: 'Pre-processing che porta ogni feature a media 0 e deviazione standard 1: $(v - \\text{media})/\\text{dev. std}$.',
    lesson: '08',
    section: 'Input e output',
  },
  {
    id: 'monk',
    term: 'MONK',
    def: 'Tre piccoli problemi artificiali di classificazione binaria (UCI) con 6 attributi simbolici, 17 input con la codifica 1-of-k: il primo collaudo di un’implementazione di una rete.',
    lesson: '08',
    section: 'Verso il progetto: il benchmark MONK',
  },
  // ------------------------------------------------------------------ 09
  {
    id: 'blind-test-set',
    term: 'Blind test set',
    def: 'Test set «cieco»: mai guardato durante lo sviluppo, usato solo per la valutazione finale. Se si usa per scegliere il modello non è più un test set.',
    lesson: '09',
    section: 'Test o model selection?',
  },
  {
    id: 'subset-selection-bias',
    term: 'Subset selection bias',
    def: 'La distorsione della stima che nasce quando la selezione (di feature o di modello) è fatta sull’intero dataset: il test set è stato usato implicitamente e la stima diventa ottimistica.',
    lesson: '09',
    section: 'Un controesempio istruttivo',
  },
  {
    id: 'grid-search',
    term: 'Grid search',
    def: 'Ricerca degli iperparametri che prova tutte le combinazioni di una griglia di valori, scegliendo la migliore sul validation set. Costo $(\\#\\text{valori})^{\\#\\text{iperparametri}}$.',
    lesson: '09',
    section: 'Grid search',
  },
  {
    id: 'random-search',
    term: 'Random search',
    en: 'Bergstra e Bengio, 2012',
    def: 'Ricerca degli iperparametri con combinazioni estratte a caso: con lo stesso budget prova molti più valori distinti di ciascun iperparametro, utile quando solo alcuni contano.',
    lesson: '09',
    section: 'Alternative alla grid search',
  },
  {
    id: 'stratificazione',
    term: 'Stratificazione',
    def: 'Campionare in modo che ogni partizione (TR, TS, fold) contenga le classi circa nelle stesse proporzioni del dataset completo.',
    lesson: '09',
    section: 'Campionamento fortunato o sfortunato',
  },
  {
    id: 'bootstrap',
    term: 'Bootstrap',
    def: 'Ricampionamento casuale con reinserimento, ripetuto per ottenere sottoinsiemi diversi di validazione o di test.',
    lesson: '09',
    section: 'Misure d’errore per la valutazione',
  },
  // ------------------------------------------------------------------ 10
  {
    id: 'iid',
    term: 'i.i.d.',
    en: 'indipendenti e identicamente distribuiti',
    def: 'Dati estratti tutti dalla stessa distribuzione $p(z)$, ciascuno indipendentemente dagli altri: l’ipotesi su cui poggiano le stime del rischio.',
    lesson: '10',
    section: 'Notazione',
  },
  {
    id: 'leave-one-out',
    term: 'Leave-one-out CV',
    en: 'LOOCV',
    def: 'La K-fold cross-validation con $K = l$: ogni fold contiene un solo esempio, che a turno viene lasciato fuori.',
    lesson: '10',
    section: 'K-fold cross-validation',
  },
  {
    id: 'design-set',
    term: 'Design set',
    def: 'La parte dei dati usata per costruire il modello finale (training e validazione), separata dal test set.',
    lesson: '10',
    section: 'K-fold CV per la selezione + hold-out per il test',
  },
  {
    id: 'double-cv',
    term: 'Double (nested) cross-validation',
    def: 'Per ogni fold esterno, una cross-validation interna sugli altri dati sceglie gli iperparametri; la media degli errori sui fold esterni stima il rischio della classe di modelli. Non restituisce un modello unico.',
    lesson: '10',
    section: 'Double (nested) K-fold CV',
  },
  // ------------------------------------------------------------------ 11
  {
    id: 'ensemble',
    term: 'Ensemble',
    def: 'Uso di più modelli insieme, combinandone le uscite (media o voto) invece di sceglierne uno.',
    lesson: '11',
    section: 'Inizializzazione casuale e model selection',
  },
  {
    id: 'selezione-sequenziale',
    term: 'Selezione sequenziale degli iperparametri',
    def: 'Scegliere gli iperparametri uno alla volta (es. prima $\\eta$, poi il numero di unità): introduce un bias legato all’ordine, perché ignora gli effetti incrociati. Va evitata a favore di una griglia su tutte le combinazioni.',
    lesson: '11',
    section: 'Selezione sequenziale degli iperparametri',
  },
  // ------------------------------------------------------------------ 12
  {
    id: 'dicotomia',
    term: 'Dicotomia',
    def: 'Una delle $2^N$ possibili etichettature ($-1$ o $+1$) di $N$ punti. È rappresentata in $H$ se qualche ipotesi di $H$ la realizza.',
    lesson: '12',
    section: 'Shattering',
  },
  {
    id: 'shattering',
    term: 'Shattering',
    en: 'frammentazione',
    def: '$H$ frammenta un insieme di punti se rappresenta tutte le sue dicotomie, cioè classifica senza errori i punti per ogni possibile etichettatura.',
    lesson: '12',
    section: 'Shattering',
  },
  {
    id: 'rischio-garantito',
    term: 'Rischio garantito',
    def: 'Il membro destro del VC-bound, $R_{emp} + \\varepsilon$: con probabilità almeno $1-\\delta$ il rischio vero non lo supera.',
    lesson: '12',
    section: 'Il bound analitico sul rischio',
  },
  // ------------------------------------------------------------------ 13
  {
    id: 'svm',
    term: 'Support Vector Machine',
    en: 'SVM',
    def: 'Macchina lineare che, tra gli iperpiani separatori, sceglie quello a margine massimo: realizza una SRM. Con soft margin e kernel tratta dati rumorosi e confini non lineari.',
    lesson: '13',
    section: 'Parte I — SVM per la classificazione binaria',
  },
  {
    id: 'margine',
    term: 'Margine di separazione',
    def: 'Il doppio della distanza tra l’iperpiano e il punto più vicino, quando l’iperpiano è equidistante dalle due classi: $\\rho = 2/\\|\\mathbf{w}\\|$ in forma canonica.',
    lesson: '13',
    section: 'Il margine di separazione',
  },
  {
    id: 'iperpiano-ottimo',
    term: 'Iperpiano ottimo',
    def: 'L’iperpiano separatore che massimizza il margine, cioè minimizza $\\|\\mathbf{w}\\|$; è unico.',
    lesson: '13',
    section: 'Il margine di separazione',
  },
  {
    id: 'support-vector',
    term: 'Support vector',
    def: 'Pattern che soddisfa il vincolo con l’uguaglianza, $d_i(\\mathbf{w}^T\\mathbf{x}_i + b) = 1$ (con slack, $1 - \\xi_i$): ha moltiplicatore $\\alpha_i > 0$ e da solo determina la soluzione.',
    lesson: '13',
    section: 'Rappresentazione canonica e support vector',
  },
  {
    id: 'soft-margin',
    term: 'Soft margin',
    def: 'SVM che ammette punti dentro il margine o dal lato sbagliato, pagandone le variabili slack con peso $C$: margine più ampio e tolleranza al rumore.',
    lesson: '13',
    section: 'SVM soft margin: ammettere errori',
  },
  {
    id: 'variabili-slack',
    term: 'Variabili slack',
    def: 'Variabili $\\xi_i \\ge 0$ che rilassano i vincoli, $d_i(\\mathbf{w}^T\\mathbf{x}_i + b) \\ge 1 - \\xi_i$: 0 fuori dal margine, tra 0 e 1 dentro il margine, oltre 1 per un errore.',
    lesson: '13',
    section: 'Variabili slack',
  },
  {
    id: 'kernel',
    term: 'Kernel',
    en: 'inner product kernel',
    def: 'Funzione simmetrica $k(\\mathbf{x}_i, \\mathbf{x}) = \\Phi^T(\\mathbf{x}_i)\\Phi(\\mathbf{x})$ che calcola il prodotto scalare nello spazio delle feature senza calcolare la mappatura $\\Phi$.',
    lesson: '13',
    section: 'Il kernel trick',
  },
  {
    id: 'kernel-trick',
    term: 'Kernel trick',
    def: 'Sostituire ogni prodotto scalare tra pattern (nel duale e nella decisione) con un kernel: si lavora in spazi delle feature altissimi o infiniti senza mai costruirli.',
    lesson: '13',
    section: 'Il kernel trick',
  },
  {
    id: 'matrice-kernel',
    term: 'Matrice kernel',
    en: 'matrice di Gram',
    def: 'La matrice $N \\times N$ simmetrica $K_{ij} = k(\\mathbf{x}_i, \\mathbf{x}_j)$ dei prodotti scalari tra i pattern di training nello spazio delle feature.',
    lesson: '13',
    section: 'La matrice kernel',
  },
  {
    id: 'mercer',
    term: 'Teorema di Mercer',
    def: 'Una funzione è un kernel valido (un prodotto scalare in qualche spazio) se produce matrici kernel semidefinite positive, cioè con autovalori non negativi.',
    lesson: '13',
    section: 'La matrice kernel',
  },
  // ------------------------------------------------------------------ 14
  {
    id: 'metodi-kernel',
    term: 'Metodi kernel',
    en: 'kernelizzazione',
    def: 'Modelli in cui ogni prodotto scalare o misura di similarità è sostituito da un kernel: lavorano in uno spazio delle feature implicito cambiando solo il kernel, anche su stringhe, alberi e grafi.',
    lesson: '14',
    section: 'Metodi kernel',
  },
  // ------------------------------------------------------------------ 15
  {
    id: 'bias-statistico',
    term: 'Bias (di un modello)',
    def: 'La discrepanza $\\big(\\bar h(\\mathbf{x}) - f(\\mathbf{x})\\big)^2$ tra la funzione vera e la predizione **media** sui diversi training set: un errore sistematico, dovuto a uno spazio $H$ troppo piccolo o a un modello troppo rigido.',
    lesson: '15',
    section: 'Interpretazione delle tre componenti',
  },
  {
    id: 'varianza-modello',
    term: 'Varianza (di un modello)',
    def: 'La variabilità della risposta del modello per diverse realizzazioni del training set, $E_P\\big[(h(\\mathbf{x}) - \\bar h(\\mathbf{x}))^2\\big]$: è dovuta a una flessibilità eccessiva.',
    lesson: '15',
    section: 'Interpretazione delle tre componenti',
  },
  {
    id: 'rumore-irriducibile',
    term: 'Rumore irriducibile',
    def: 'La componente $\\sigma^2$ dell’errore atteso dovuta all’errore casuale nelle etichette: anche la soluzione ottima può sbagliare, e non dipende dal modello.',
    lesson: '15',
    section: 'Interpretazione delle tre componenti',
  },
  {
    id: 'bias-varianza',
    term: 'Decomposizione bias-varianza',
    def: 'L’errore di predizione atteso sui training set, con loss quadratica, è la somma di **varianza**, **bias²** e **rumore²**.',
    lesson: '15',
    section: 'La decomposizione',
  },
  {
    id: 'comitato',
    term: 'Comitato',
    def: 'Ensemble a voto: nella regressione la media semplice $o(\\mathbf{x}) = \\frac{1}{K}\\sum_i h_i(\\mathbf{x})$, nella classificazione il voto di molti classificatori. Per una loss convessa non è peggiore della media dei suoi membri.',
    lesson: '15',
    section: 'Ensemble learning',
  },
  {
    id: 'stacking',
    term: 'Stacking',
    def: 'Ensemble in cui il combinatore delle risposte dei modelli è a sua volta un modello di ML.',
    lesson: '15',
    section: 'Ensemble learning',
  },
  {
    id: 'bagging',
    term: 'Bagging',
    en: 'bootstrap aggregating',
    def: 'Si addestrano $K$ modelli su sottoinsiemi diversi del training set ottenuti con il bootstrap e se ne fa la media (regressione) o il voto (classificazione): la media riduce la varianza senza aumentare il bias.',
    lesson: '15',
    section: 'Bagging (bootstrap aggregating)',
  },
  {
    id: 'boosting',
    term: 'Boosting',
    en: 'es. AdaBoost',
    def: 'Classificatori addestrati in sequenza, ognuno concentrato sulle istanze sbagliate dai precedenti, e combinati con un voto pesato in base all’errore. Soffre con dati rumorosi.',
    lesson: '15',
    section: 'Boosting (es. AdaBoost)',
  },
  {
    id: 'weak-learner',
    term: 'Weak learner',
    def: 'Classificatore appena migliore del caso (errore minore di $1/2$ nel binario): il boosting ne combina molti per costruire in modo incrementale modelli complessi.',
    lesson: '15',
    section: 'Boosting (es. AdaBoost)',
  },
  // ------------------------------------------------------------------ 16
  {
    id: 'cnn',
    term: 'Rete convoluzionale',
    en: 'CNN, ConvNet',
    def: 'Rete feedforward non completamente connessa basata su quattro ingredienti: **connessioni locali**, **pesi condivisi**, **pooling** e **molti strati**. Un’istanza storica di rete profonda.',
    lesson: '16',
    section: 'La CNN nel complesso',
  },
  {
    id: 'campo-recettivo',
    term: 'Campo recettivo locale',
    def: 'La piccola zona dell’input (ad esempio $3 \\times 3$ pixel) a cui un’unità è collegata. Negli strati più alti le unità sono collegate indirettamente ad aree sempre più grandi dell’immagine.',
    lesson: '16',
    section: 'Il problema: riconoscere caratteri',
  },
  {
    id: 'weight-sharing',
    term: 'Condivisione dei pesi',
    en: 'weight sharing',
    def: 'Unità diverse usano gli stessi pesi, cioè applicano la stessa operazione a parti diverse dell’input: riduce i parametri liberi pur mantenendo una connettività complessa.',
    lesson: '16',
    section: 'Il problema: riconoscere caratteri',
  },
  {
    id: 'convoluzione',
    term: 'Convoluzione',
    def: 'Media pesata di una funzione $f$ con pesi dati da una funzione $g$ che scorre: $(f * g)(t) = \\int f(\\tau)\\,g(t-\\tau)\\,d\\tau$. In una rete è una finestra scorrevole di pesi condivisi.',
    lesson: '16',
    section: 'La convoluzione',
  },
  {
    id: 'tdnn',
    term: 'Time-Delay Neural Network',
    def: 'Rete in cui la stessa unità (un filtro adattivo con pesi condivisi) scorre su una sequenza di input: la convoluzione 1D.',
    lesson: '16',
    section: 'Convoluzione 1D: una unità su uno stream',
  },
  {
    id: 'kernel-convoluzione',
    term: 'Kernel (di convoluzione)',
    en: 'filtro',
    def: 'I pesi dell’unità che scorre sull’immagine, ad esempio $3 \\times 3$: è il suo campo recettivo locale, un filtro addestrato a rilevare un pattern.',
    lesson: '16',
    section: 'Convoluzione 2D',
  },
  {
    id: 'stride',
    term: 'Stride',
    def: 'Di quanti pixel si sposta il kernel a ogni passo. Con stride maggiore di 1 il kernel salta pixel: è un sotto-campionamento e la feature map si riduce.',
    lesson: '16',
    section: 'Convoluzione 2D',
  },
  {
    id: 'padding',
    term: 'Padding',
    def: 'Il bordo aggiunto attorno all’immagine per gestire le posizioni in cui il kernel esce dai margini.',
    lesson: '16',
    section: 'Convoluzione 2D',
  },
  {
    id: 'feature-map',
    term: 'Feature map',
    def: 'L’uscita di un filtro che ha percorso tutta l’immagine: le feature estratte dal filtro, posizione per posizione.',
    lesson: '16',
    section: 'Convoluzione 2D',
  },
  {
    id: 'invarianza-traslazione',
    term: 'Invarianza per traslazione',
    def: 'Le feature vengono rilevate indipendentemente dalla posizione, perché lo stesso filtro è applicato su tutta l’immagine.',
    lesson: '16',
    section: 'Una rete di «filtri»',
  },
  {
    id: 'pooling',
    term: 'Pooling',
    en: 'max pooling',
    def: 'Riduzione della feature map: un valore (la media o, nel **max pooling**, il massimo) per ogni insieme rettangolare di pixel. Aiuta l’invarianza a piccole traslazioni.',
    lesson: '16',
    section: 'Pooling',
  },
  {
    id: 'data-augmentation',
    term: 'Data augmentation',
    def: 'Ottenere molti più esempi di training deformando quelli disponibili (ad esempio le immagini): un modo di controllare la complessità.',
    lesson: '16',
    section: 'MNIST',
  },
  {
    id: 'capsule-network',
    term: 'Capsule Network',
    def: 'Reti con «capsule», gruppi di neuroni che indicano se un’entità è presente e i suoi parametri di posa; al posto del max pooling usano un meccanismo di routing.',
    lesson: '16',
    section: 'CNN moderne e GPU',
  },
  // ------------------------------------------------------------------ 17
  {
    id: 'deep-learning',
    term: 'Deep learning',
    def: 'Modelli composti da più strati di elaborazione non lineare che apprendono rappresentazioni dei dati con più livelli di astrazione: una rappresentazione gerarchica, sparsa e distribuita.',
    lesson: '17',
    section: 'Che cos’è il deep learning',
  },
  {
    id: 'shallow',
    term: 'Modello shallow',
    en: 'superficiale',
    def: 'Modello con pochi strati (ad esempio una rete con meno di 3 strati), contrapposto ai modelli profondi.',
    lesson: '17',
    section: 'Il quadro generale',
  },
  {
    id: 'feature-learning',
    term: 'Feature learning',
    def: 'Apprendere le rappresentazioni dei dati (estrazione gerarchica di feature) invece di progettarle a mano (*feature engineering*).',
    lesson: '17',
    section: 'Gli ingredienti concettuali: astrazione gerarchica',
  },
  {
    id: 'no-flattening',
    term: 'No-flattening',
    def: 'Una funzione rappresentata in modo compatto da un’architettura profonda può richiedere un’architettura molto più grande (anche esponenzialmente) se la profondità è insufficiente. Riguarda l’efficienza, non l’espressività.',
    lesson: '17',
    section: 'Un esempio dai circuiti logici',
  },
  {
    id: 'composizionalita',
    term: 'Composizionalità',
    def: 'I concetti semplici rappresentati in uno strato sono usati come **primitive** dallo strato successivo per rappresentare concetti più complessi, senza apprendere tutte le combinazioni in modo esplicito.',
    lesson: '17',
    section: 'Perché: la composizionalità',
  },
  {
    id: 'representation-learning',
    term: 'Representation learning',
    def: 'Metodi che permettono a una macchina di ricevere dati grezzi e scoprire automaticamente le rappresentazioni necessarie per il rilevamento o la classificazione.',
    lesson: '17',
    section: 'Representation learning',
  },
  {
    id: 'pre-training',
    term: 'Pre-training',
    en: 'greedy layer-wise unsupervised pretraining',
    def: 'Apprendimento non supervisionato, strato per strato, usato per inizializzare una rete profonda prima dell’addestramento supervisionato: una buona inizializzazione e una forma di regolarizzazione.',
    lesson: '17',
    section: 'Pre-training',
  },
  {
    id: 'autoencoder',
    term: 'Autoencoder',
    def: 'Rete addestrata a copiare il proprio input in uscita: un **encoder** $\\mathbf{h} = f(\\mathbf{x})$ produce il codice, un **decoder** la ricostruzione $\\mathbf{r} = g(\\mathbf{h})$. Undercomplete o overcomplete secondo la dimensione dello strato nascosto.',
    lesson: '17',
    section: 'Autoencoder',
  },
  {
    id: 'fine-tuning',
    term: 'Fine-tuning',
    def: 'L’addestramento finale di tutti i parametri di una rete già inizializzata (con il pre-training o da un modello pre-addestrato) rispetto al criterio supervisionato.',
    lesson: '17',
    section: 'L’algoritmo di pre-training (Bengio)',
  },
  {
    id: 'transfer-learning',
    term: 'Transfer learning',
    def: 'Usare la rappresentazione scoperta da un modello per migliorarne un altro: multi-task learning, domain adaptation, riuso di modelli pre-addestrati.',
    lesson: '17',
    section: 'Transfer learning',
  },
  {
    id: 'rappresentazione-distribuita',
    term: 'Rappresentazione distribuita',
    def: 'Rappresentazione in cui le feature non sono mutuamente esclusive: ogni concetto è l’insieme delle attivazioni di tutte le unità. Con $n$ feature a $k$ valori descrive $k^n$ concetti, contro gli $n$ di una one-hot.',
    lesson: '17',
    section: 'Rappresentazioni distribuite',
  },
  {
    id: 'word-embedding',
    term: 'Word embedding',
    en: 'es. word2vec',
    def: 'Rappresentazione distribuita delle parole appresa dai dati: parole che compaiono in contesti simili, quindi di significato simile, finiscono vicine.',
    lesson: '17',
    section: 'Attributi condivisi: separare i concetti',
  },
  {
    id: 'double-descent',
    term: 'Double descent',
    def: 'Al crescere della dimensione del modello l’errore di test prima scende, poi risale (la classica U), e poi scende di nuovo oltre la soglia di interpolazione, dove l’errore di training è quasi zero.',
    lesson: '17',
    section: 'Altri spunti e risultati recenti',
  },
  {
    id: 'lottery-ticket',
    term: 'Lottery ticket hypothesis',
    def: 'Le buone prestazioni di una rete grande dipendono dall’inizializzazione fortunata di una o più sotto-reti: le reti grandi ne contengono esponenzialmente di più.',
    lesson: '17',
    section: 'Altri spunti e risultati recenti',
  },
  {
    id: 'vanishing-gradient',
    term: 'Vanishing gradient',
    en: 'ed exploding gradient',
    def: 'Retropropagato attraverso molti strati, il gradiente si riduce esponenzialmente (pesi piccoli, derivate delle sigmoidi) oppure cresce esponenzialmente (pesi grandi, *exploding gradient*).',
    lesson: '17',
    section: 'Il vanishing gradient',
  },
  {
    id: 'gradient-clipping',
    term: 'Gradient clipping',
    def: 'Se la norma del gradiente supera una soglia $v$, lo si riscala a norma $v$ mantenendone la direzione: evita che le «scogliere» della funzione di costo catapultino i pesi lontano.',
    lesson: '17',
    section: 'Gradient clipping',
  },
  {
    id: 'batch-normalization',
    term: 'Batch normalization',
    def: 'Normalizzazione delle attivazioni di ogni strato a media zero e varianza unitaria, con le statistiche del mini-batch: regolarizza e rende l’apprendimento più rapido.',
    lesson: '17',
    section: 'Batch normalization',
  },
  {
    id: 'dropout',
    term: 'Dropout',
    def: 'Durante l’addestramento si rimuove a caso un sottoinsieme di unità (una maschera diversa per ogni esempio): un bagging implicito di un numero esponenziale di sotto-reti che condividono i pesi, con effetto regolarizzante.',
    lesson: '17',
    section: 'Dropout',
  },
  {
    id: 'gan',
    term: 'Generative Adversarial Network',
    en: 'GAN',
    def: 'Due reti in competizione: una genera candidati, l’altra li valuta distinguendo i veri dai generati.',
    lesson: '17',
    section: 'Apprendimento avversario',
  },
  // ------------------------------------------------------------------ 18
  {
    id: 'random-forest',
    term: 'Random Forest',
    def: 'Ensemble di alberi di decisione randomizzati, ciascuno costruito su campioni estratti a caso dal training set e con una scelta casuale delle variabili su cui dividere i nodi.',
    lesson: '18',
    section: 'Modelli intrinsecamente casuali',
  },
  {
    id: 'reti-randomizzate',
    term: 'Reti neurali a pesi casuali',
    en: 'reti randomizzate',
    def: 'Reti con uno o più strati nascosti i cui pesi sono fissati dopo l’inizializzazione casuale: si addestrano solo i pesi di uscita, con un modello lineare.',
    lesson: '18',
    section: 'Reti neurali a pesi casuali',
  },
  {
    id: 'elm',
    term: 'ELM e RVFL',
    en: 'Extreme Learning Machine, Random Vector Functional Link',
    def: 'I principali modelli di rete feedforward randomizzata, insieme alle reti RBF con centri casuali.',
    lesson: '18',
    section: 'Reti neurali a pesi casuali',
  },
  {
    id: 'readout',
    term: 'Readout',
    def: 'Lo strato di uscita addestrato di una rete randomizzata: combina le feature dello spazio nascosto, tipicamente con un modello lineare, $\\mathbf{W}^{out} = (\\mathbf{H}^T\\mathbf{H} + \\lambda\\mathbf{I})^{-1}\\mathbf{H}^T\\mathbf{d}$.',
    lesson: '18',
    section: 'Struttura generale',
  },
  {
    id: 'teorema-cover',
    term: 'Teorema di Cover',
    def: 'Un problema di classificazione proiettato in modo non lineare in uno spazio ad alta dimensione ha più probabilità di essere linearmente separabile che in uno spazio a bassa dimensione, purché lo spazio non sia densamente popolato.',
    lesson: '18',
    section: 'Struttura generale',
  },
  // ------------------------------------------------------------------ 19
  {
    id: 'centroide',
    term: 'Centroide',
    en: 'prototipo, codevector',
    def: 'Il vettore che rappresenta un cluster (detto anche prototipo, vettore di riferimento, centro del cluster). L’insieme dei centroidi è il **codebook**.',
    lesson: '19',
    section: 'Clustering',
  },
  {
    id: 'quantizzazione-vettoriale',
    term: 'Quantizzazione vettoriale',
    en: 'Vector Quantization, VQ',
    def: 'Codificare i dati $\\mathbf{x} \\in V$ con un insieme finito di vettori di riferimento: ogni $\\mathbf{x}$ è descritto dal vettore **vincente**, quello a distorsione minima. Lo spazio risulta diviso in poliedri di Voronoi.',
    lesson: '19',
    section: 'Quantizzazione vettoriale',
  },
  {
    id: 'errore-di-quantizzazione',
    term: 'Errore di quantizzazione',
    en: 'distorsione',
    def: 'La distorsione quadratica media tra i dati e i loro prototipi vincitori, $E = \\sum_i\\sum_j \\|\\mathbf{x}_i - \\mathbf{w}_j\\|^2\\,\\delta_{winner}(i,j)$: la loss della quantizzazione vettoriale.',
    lesson: '19',
    section: 'L’errore di quantizzazione',
  },
  {
    id: 'k-means',
    term: 'K-means',
    def: 'Algoritmo di clustering che minimizza l’errore di quantizzazione: on-line sposta il prototipo vincitore verso il dato; in batch alterna l’assegnazione al centro più vicino e il ricalcolo dei centri come medie.',
    lesson: '19',
    section: 'K-means',
  },
  {
    id: 'som',
    term: 'Self-Organizing Map',
    en: 'SOM, mappa di Kohonen',
    def: 'Rete di neuroni disposti su una griglia a bassa dimensione, ciascuno con un peso della dimensione dell’input: impara una mappa che **preserva la topologia**, aggiornando il vincitore e i suoi vicini sulla griglia.',
    lesson: '19',
    section: 'Self-Organizing Map',
  },
  {
    id: 'apprendimento-competitivo',
    term: 'Apprendimento competitivo',
    def: 'Processo adattivo in cui i neuroni competono per un dato e il vincitore apprende di più: diventano gradualmente specializzati su categorie di input diverse.',
    lesson: '19',
    section: 'Apprendimento competitivo e ispirazione biologica',
  },
  {
    id: 'funzione-di-vicinato',
    term: 'Funzione di vicinato',
    en: 'neighborhood kernel',
    def: 'La funzione $h_{i,i^*}$ che decresce con la distanza **sulla mappa** tra l’unità $i$ e il vincitore, ad esempio $\\exp(-\\|\\mathbf{r}_i - \\mathbf{r}_{i^*}\\|^2 / 2\\sigma^2)$: decide quanto si aggiornano i vicini.',
    lesson: '19',
    section: 'Fase cooperativa',
  },
  {
    id: 'u-matrix',
    term: 'U-matrix',
    def: 'Visualizzazione delle distanze tra i prototipi di unità adiacenti di una SOM: colori scuri = grandi distanze (confini tra cluster), colori chiari = piccole distanze (cluster).',
    lesson: '19',
    section: 'Visualizzazione',
  },
  // ------------------------------------------------------------------ 20
  {
    id: 'rnn',
    term: 'Rete neurale ricorrente',
    en: 'RNN',
    def: 'Rete con connessioni di feedback (cicli): ha proprietà dinamiche e una memoria (uno stato) delle computazioni passate, e può elaborare sequenze di lunghezza variabile.',
    lesson: '20',
    section: 'Perché i dati sequenziali',
  },
  {
    id: 'trasduzione',
    term: 'Trasduzione',
    def: 'Mappatura da una sequenza di input a un valore o a una sequenza di output: classificazione di sequenze, trasduzione IO isomorfa, predizione del passo successivo, generazione di sequenze.',
    lesson: '20',
    section: 'Il nuovo dominio: sequenze e trasduzioni',
  },
  {
    id: 'idnn',
    term: 'Input Delay Neural Network',
    en: 'IDNN',
    def: 'Rete a memoria finita: una finestra scorrevole di dimensione fissa sulla sequenza (un registro a scorrimento) data in input a un MLP.',
    lesson: '20',
    section: 'Approccio 1: memoria finita (IDNN)',
  },
  {
    id: 'stato-rnn',
    term: 'Stato (di una rete ricorrente)',
    en: 'contesto',
    def: 'Il valore $x(t)$ che riassume l’informazione passata: una codifica adattiva, a valori continui, della sotto-sequenza vista finora, $x(t) = f(\\mathbf{w}^T\\mathbf{l}(t) + \\hat w\\,x(t-1) + \\theta)$.',
    lesson: '20',
    section: 'Approccio 2: unità ricorrenti',
  },
  {
    id: 'simple-rnn',
    term: 'Simple RNN',
    en: 'rete di Elman',
    def: 'Rete con molte unità ricorrenti nascoste, ciascuna delle quali riceve l’input e gli stati precedenti di tutte le unità nascoste: $\\mathbf{x}(t) = f(W\\mathbf{l}(t) + \\hat W\\mathbf{x}(t-1) + \\boldsymbol{\\theta})$.',
    lesson: '20',
    section: 'Una rete ricorrente (Simple RNN)',
  },
  {
    id: 'unfolding',
    term: 'Unfolding',
    en: 'rete di codifica',
    def: 'Srotolare la rete ricorrente nel tempo: una replica del modello per ogni passo della sequenza, con i pesi condivisi. Si ottiene una rete feedforward equivalente su cui applicare la backpropagation.',
    lesson: '20',
    section: 'Apprendimento: l’unfolding',
  },
  {
    id: 'bptt',
    term: 'BPTT',
    en: 'Back-Propagation Through Time',
    def: 'La backpropagation applicata alla rete srotolata nel tempo; insieme a RTRL (*Real-Time Recurrent Learning*) è l’algoritmo di apprendimento supervisionato delle RNN.',
    lesson: '20',
    section: 'Apprendimento: l’unfolding',
  },
  {
    id: 'lstm',
    term: 'LSTM',
    en: 'Long Short-Term Memory',
    def: 'RNN con unità «gate» che selezionano il flusso del passato e del gradiente, per apprendere dipendenze a lungo termine nonostante il vanishing gradient. Le GRU ne sono una versione semplificata.',
    lesson: '20',
    section: 'Modelli avanzati',
  },
  {
    id: 'transformer',
    term: 'Transformer',
    def: 'Architettura basata sull’attenzione multi-head: lo strato di attenzione pesa tutti gli stati precedenti secondo una rilevanza appresa, così il modello accede a qualunque punto della sequenza.',
    lesson: '20',
    section: 'Transformer e attenzione',
  },
  {
    id: 'reservoir-computing',
    term: 'Reservoir Computing',
    def: 'Reti ricorrenti connesse casualmente con pesi fissi (il reservoir), il cui stato codifica le sequenze; si addestra solo la mappatura di uscita.',
    lesson: '20',
    section: 'Reti ricorrenti randomizzate: le Echo State Network',
  },
  {
    id: 'esn',
    term: 'Echo State Network',
    en: 'ESN',
    def: 'Un grande reservoir di unità ricorrenti sparse non addestrate e un readout lineare addestrato. **Echo State Property**: con una transizione di stato contrattiva lo stato dipende solo dalla storia degli input, non dallo stato iniziale.',
    lesson: '20',
    section: 'Reti ricorrenti randomizzate: le Echo State Network',
  },
  {
    id: 'recnn',
    term: 'Rete neurale ricorsiva',
    en: 'RecNN',
    def: 'Estensione delle RNN agli alberi: lo stato di ogni vertice dipende dal suo label e dagli stati dei figli, e la codifica procede dalle foglie alla radice.',
    lesson: '20',
    section: 'Verso i domini strutturati',
  },
]

export const glossaryById = new Map(glossary.map((g) => [g.id, g]))
