/**
 * Glossario: definizioni brevi, tratte dagli appunti.
 * `section` è il titolo della sezione in cui il termine è spiegato (serve per il link).
 */
export type GlossaryEntry = {
  id: string
  term: string
  en?: string
  def: string
  lesson: string
  section: string
}

export const glossary: GlossaryEntry[] = [
  // ------------------------------------------------------------------ 01
  {
    id: 'machine-learning',
    term: 'Machine Learning',
    en: 'apprendimento automatico',
    def: 'Apprendimento automatico, da parte di un sistema, a partire dall’**esperienza** (un insieme di esempi), finalizzato a risolvere un compito computazionale.',
    lesson: '01',
    section: 'Che cos’è il Machine Learning',
  },
  {
    id: 'prodotto-scalare',
    term: 'Prodotto scalare',
    en: 'inner / dot product',
    def: '$\\mathbf{a}\\cdot\\mathbf{b}=\\sum_i a_i b_i=|\\mathbf{a}||\\mathbf{b}|\\cos\\theta$. Misura quanto due vettori puntano nella stessa direzione: massimo se paralleli, nullo se ortogonali, negativo se opposti.',
    lesson: '01',
    section: 'Prodotto scalare e norme',
  },
  {
    id: 'norma',
    term: 'Norma euclidea',
    def: '$\\|\\mathbf{x}\\|_2=\\sqrt{\\mathbf{x}^T\\mathbf{x}}=\\sqrt{\\sum_i x_i^2}$: la lunghezza del vettore, cioè la sua distanza dall’origine.',
    lesson: '01',
    section: 'Prodotto scalare e norme',
  },
  {
    id: 'tensore',
    term: 'Tensore',
    def: 'Nella visione semplificata del ML, un array multidimensionale di numeri su una griglia regolare con un numero variabile di assi (es. $X_{i,j,k}$).',
    lesson: '01',
    section: 'Prodotto scalare e norme',
  },
  {
    id: 'gradiente',
    term: 'Gradiente',
    def: 'Il vettore delle derivate parziali $\\nabla f=(\\partial f/\\partial x_1,\\dots,\\partial f/\\partial x_n)$. Punta nella direzione di **massima crescita** di $f$; la sua norma dice quanto è ripida la pendenza.',
    lesson: '01',
    section: 'Derivate parziali e gradiente',
  },
  {
    id: 'discesa-del-gradiente',
    term: 'Discesa del gradiente',
    en: 'gradient descent',
    def: 'Idea alla base dell’addestramento: muoversi nella direzione $-\\nabla f$, quella in cui la funzione di errore **decresce** più rapidamente.',
    lesson: '01',
    section: 'Derivate parziali e gradiente',
  },
  {
    id: 'punto-stazionario',
    term: 'Punto stazionario',
    def: 'Punto in cui il gradiente è nullo. Può essere un minimo locale, un massimo locale o un punto di sella: il gradiente nullo da solo non basta a dirlo.',
    lesson: '01',
    section: 'Derivate parziali e gradiente',
  },
  {
    id: 'gaussiana',
    term: 'Gaussiana',
    en: 'distribuzione normale',
    def: 'Densità $f(x)=\\frac{1}{\\sigma\\sqrt{2\\pi}}e^{-(x-\\mu)^2/(2\\sigma^2)}$ con media $\\mu$ e varianza $\\sigma^2$. Con $\\mu=0,\\ \\sigma^2=1$ è la normale standard.',
    lesson: '01',
    section: 'Densità di probabilità: la gaussiana',
  },

  // ------------------------------------------------------------------ 03
  {
    id: 'pattern',
    term: 'Pattern',
    en: 'esempio, istanza, campione',
    def: 'Una riga $\\mathbf{x}$ del dataset. $\\mathbf{x}_p$ è il $p$-esimo pattern; il dataset ne contiene $l$.',
    lesson: '03',
    section: 'Dati',
  },
  {
    id: 'feature',
    term: 'Feature',
    en: 'attributo, componente',
    def: 'Una delle $n$ proprietà che descrivono ogni esempio: $x_i$ è la $i$-esima feature di $\\mathbf{x}$.',
    lesson: '03',
    section: 'Dati',
  },
  {
    id: 'one-hot',
    term: 'Codifica one-hot',
    en: '1-of-k',
    def: 'Ogni simbolo diventa un vettore con un solo 1, es. $A=(1,0,0)$, $B=(0,1,0)$, $C=(0,0,1)$: tutti i simboli risultano **equidistanti**.',
    lesson: '03',
    section: 'Codifica delle variabili categoriche',
  },
  {
    id: 'rumore',
    term: 'Rumore',
    en: 'noise',
    def: 'Fattori esterni aggiunti al segnale informativo, dovuti alla casualità delle misure e non alla legge sottostante (es. rumore gaussiano).',
    lesson: '03',
    section: 'Rumore, outlier e feature selection',
  },
  {
    id: 'outlier',
    term: 'Outlier',
    def: 'Valore insolito, incoerente con la maggior parte delle osservazioni. Si rimuove in pre-elaborazione o si usano metodi **robusti**.',
    lesson: '03',
    section: 'Rumore, outlier e feature selection',
  },
  {
    id: 'feature-selection',
    term: 'Feature selection',
    def: 'Selezione di un piccolo numero di feature informative, per una rappresentazione ottimale dell’input.',
    lesson: '03',
    section: 'Rumore, outlier e feature selection',
  },
  {
    id: 'supervisionato',
    term: 'Apprendimento supervisionato',
    def: 'Si apprende da esempi **etichettati** $\\langle\\mathbf{x},d\\rangle$, con il target $d$ fornito da un “insegnante”, per trovare un’ipotesi $h$ che approssimi $f$ e generalizzi.',
    lesson: '03',
    section: 'Apprendimento supervisionato',
  },
  {
    id: 'non-supervisionato',
    term: 'Apprendimento non supervisionato',
    def: 'Nessun insegnante: solo dati non etichettati $\\langle\\mathbf{x}\\rangle$. Obiettivi tipici: clustering, riduzione di dimensionalità, stima della densità.',
    lesson: '03',
    section: 'Apprendimento non supervisionato',
  },
  {
    id: 'classificazione',
    term: 'Classificazione',
    def: 'Task supervisionato con target **categorico**: $f(\\mathbf{x})\\in\\{1,\\dots,K\\}$. Geometricamente, divide lo spazio degli input in regioni di decisione.',
    lesson: '03',
    section: 'Classificazione',
  },
  {
    id: 'concept-learning',
    term: 'Concept learning',
    def: 'Classificazione binaria: imparare una funzione booleana (vero/falso, $0/1$, $-1/+1$).',
    lesson: '03',
    section: 'Classificazione',
  },
  {
    id: 'ltu',
    term: 'Linear Threshold Unit',
    en: 'LTU',
    def: 'Classificatore $h(\\mathbf{x})=\\operatorname{sign}(\\mathbf{w}^T\\mathbf{x}+w_0)$: separa lo spazio degli input con un iperpiano.',
    lesson: '03',
    section: 'Classificazione',
  },
  {
    id: 'regressione',
    term: 'Regressione',
    def: 'Task supervisionato con target **numerico**: stima di una funzione a valori reali a partire da campioni rumorosi $(\\mathbf{x}, f(\\mathbf{x})+\\text{rumore})$.',
    lesson: '03',
    section: 'Regressione',
  },
  {
    id: 'clustering',
    term: 'Clustering',
    def: 'Partizione dei dati in sottoinsiemi di elementi “simili”, ognuno rappresentato da un centroide (prototipo).',
    lesson: '03',
    section: 'Apprendimento non supervisionato',
  },
  {
    id: 'self-supervised',
    term: 'Self-supervised learning',
    def: 'Apprendimento supervisionato con etichette generate automaticamente dalla struttura dei dati (es. predire la parola successiva). È alla base del pre-addestramento degli LLM.',
    lesson: '03',
    section: 'Altri paradigmi',
  },
  {
    id: 'reinforcement-learning',
    term: 'Reinforcement learning',
    def: 'Apprendimento con un “critico” che dice giusto/sbagliato: si impara una **politica** su come agire; ogni azione ha un effetto sull’ambiente, che risponde con un feedback.',
    lesson: '03',
    section: 'Altri paradigmi',
  },
  {
    id: 'funzione-target',
    term: 'Funzione target',
    def: 'La vera funzione $f$, sconosciuta, che si vuole approssimare. È nota solo nei punti degli esempi.',
    lesson: '03',
    section: 'Modello',
  },
  {
    id: 'ipotesi',
    term: 'Ipotesi',
    def: 'Una funzione $h$ proposta, che si ritiene simile alla funzione target $f$.',
    lesson: '03',
    section: 'Modello',
  },
  {
    id: 'spazio-delle-ipotesi',
    term: 'Spazio delle ipotesi',
    def: 'L’insieme $H$ di tutte le ipotesi che l’algoritmo di apprendimento può, in linea di principio, produrre. È il modello a definirlo.',
    lesson: '03',
    section: 'Modello',
  },
  {
    id: 'no-free-lunch',
    term: 'No Free Lunch',
    def: 'Non esiste un metodo di apprendimento universalmente migliore: se vince su alcuni problemi, deve perdere su altri.',
    lesson: '03',
    section: 'Modello',
  },
  {
    id: 'bias-induttivo',
    term: 'Bias induttivo',
    def: 'Le assunzioni sulla natura della funzione target — vincoli sul modello (**language bias**) o preferenze nella ricerca (**search bias**). Senza bias non c’è generalizzazione.',
    lesson: '03',
    section: 'Il bias induttivo',
  },
  {
    id: 'language-bias',
    term: 'Language bias',
    def: 'Bias induttivo dato da vincoli sullo spazio delle ipotesi $H$: si restringe ciò che il modello può esprimere.',
    lesson: '03',
    section: 'Il bias induttivo',
  },
  {
    id: 'search-bias',
    term: 'Search bias',
    def: 'Bias induttivo affidato alla strategia di ricerca dell’algoritmo, che privilegia certe soluzioni rispetto ad altre. È quello preferito nel ML moderno.',
    lesson: '03',
    section: 'Language bias o search bias?',
  },
  {
    id: 'version-space',
    term: 'Version space',
    def: 'Il sottoinsieme $VS_{H,TR}$ delle ipotesi di $H$ **consistenti** con tutti gli esempi di training, cioè con $h(\\mathbf{x})=d(\\mathbf{x})$ su ogni esempio.',
    lesson: '03',
    section: 'Restringere lo spazio: le regole congiuntive',
  },
  {
    id: 'lookup-table',
    term: 'Lookup table',
    def: 'Un *rote learner*: memorizza gli esempi e classifica solo input già visti (altrimenti “nessuna risposta”). Nessun bias, nessuna generalizzazione.',
    lesson: '03',
    section: 'Imparare funzioni booleane: un problema mal posto',
  },
  {
    id: 'unbiased-learner',
    term: 'Unbiased learner',
    def: 'Learner con $H=\\mathcal{P}(X)$, capace di esprimere ogni concetto. Classifica senza ambiguità solo gli esempi di training: non può generalizzare.',
    lesson: '03',
    section: 'L’unbiased learner',
  },
  {
    id: 'loss',
    term: 'Funzione di loss',
    def: '$L(h_\\mathbf{w}(\\mathbf{x}),d)$: misura, sul singolo pattern, la distanza tra l’uscita del modello e il target. Un valore alto indica un’approssimazione scarsa.',
    lesson: '03',
    section: 'Task e funzioni di loss',
  },
  {
    id: 'errore',
    term: 'Errore (rischio, loss)',
    def: 'Valore atteso della loss, ad esempio la media sugli $l$ esempi: $E(\\mathbf{w})=\\frac1l\\sum_p L(h_\\mathbf{w}(\\mathbf{x}_p),d_p)$. È la funzione obiettivo del training.',
    lesson: '03',
    section: 'Task e funzioni di loss',
  },
  {
    id: 'mse',
    term: 'Mean Squared Error',
    en: 'MSE',
    def: 'Media degli errori quadratici $(d_p-h_\\mathbf{w}(\\mathbf{x}_p))^2$ sul dataset: la loss tipica della regressione.',
    lesson: '03',
    section: 'Regressione: errore quadratico',
  },
  {
    id: 'generalizzazione',
    term: 'Generalizzazione',
    def: 'Quanto accuratamente il modello predice su **dati nuovi**, mai visti. È il concetto fondamentale del corso; si stima con un test set tenuto da parte.',
    lesson: '03',
    section: 'Generalizzazione e validazione',
  },

  // ------------------------------------------------------------------ 04
  {
    id: 'overfitting',
    term: 'Overfitting',
    def: 'Il learner restituisce $h$ quando esiste $h’\\in H$ con errore di training maggiore ($E’>E$) ma errore vero minore ($R’<R$): il modello si adatta troppo ai dati, rumore compreso.',
    lesson: '04',
    section: 'Generalizzazione e overfitting',
  },
  {
    id: 'underfitting',
    term: 'Underfitting',
    def: 'Il modello è troppo semplice rispetto alla funzione target e non ne coglie l’andamento: errore alto già sui dati di training.',
    lesson: '04',
    section: 'Effetto del grado del polinomio',
  },
  {
    id: 'erms',
    term: 'Errore RMS',
    en: 'Root-Mean-Square',
    def: '$E_{RMS}=\\sqrt{2E(\\mathbf{w}^*)/l}$: dividere per $l$ rende confrontabili dataset di dimensione diversa, la radice riporta l’errore sulla scala del target.',
    lesson: '04',
    section: 'Errore di training e di test al variare di $M$',
  },
  {
    id: 'regolarizzazione',
    term: 'Regolarizzazione',
    def: 'Penalizzare i pesi grandi per controllare la complessità del modello. Nasce dall’osservazione che l’overfitting produce coefficienti enormi.',
    lesson: '04',
    section: 'Errore di training e di test al variare di $M$',
  },
  {
    id: 'rischio',
    term: 'Rischio',
    en: 'errore vero',
    def: '$R=\\int L(d,h(\\mathbf{x}))\\,dP(\\mathbf{x},d)$: l’errore atteso su **tutti** i dati possibili, secondo la distribuzione (sconosciuta) $P$.',
    lesson: '04',
    section: 'Il setting formale (semplificato)',
  },
  {
    id: 'rischio-empirico',
    term: 'Rischio empirico',
    def: '$R_{emp}=\\frac1l\\sum_p (d_p-h(\\mathbf{x}_p))^2$: l’errore calcolato sul training set, l’unico che possiamo misurare direttamente.',
    lesson: '04',
    section: 'Il setting formale (semplificato)',
  },
  {
    id: 'erm',
    term: 'ERM',
    en: 'Empirical Risk Minimization',
    def: 'Principio induttivo: si scelgono i parametri che minimizzano il rischio empirico $R_{emp}$, sperando che approssimi il rischio vero $R$.',
    lesson: '04',
    section: 'Il setting formale (semplificato)',
  },
  {
    id: 'vc-dimension',
    term: 'VC-dimension',
    def: 'Misura della complessità di $H$, cioè della sua flessibilità nell’adattarsi ai dati (per modelli lineari o polinomi è legata al numero di parametri).',
    lesson: '04',
    section: 'VC-dimension e bound sul rischio',
  },
  {
    id: 'vc-confidence',
    term: 'VC-confidence',
    def: 'Il termine $\\varepsilon$ del VC-bound $R\\le R_{emp}+\\varepsilon$: cresce con la VC-dimension, decresce con il numero di dati $l$.',
    lesson: '04',
    section: 'VC-dimension e bound sul rischio',
  },
  {
    id: 'srm',
    term: 'Structural Risk Minimization',
    en: 'SRM',
    def: 'Minimizzare il bound $R_{emp}+\\varepsilon$ invece del solo $R_{emp}$: un compromesso tra complessità (VC-dim) e accuratezza sul training.',
    lesson: '04',
    section: 'VC-dimension e bound sul rischio',
  },
  {
    id: 'model-selection',
    term: 'Model selection',
    def: 'Stimare l’errore di generalizzazione di **diversi modelli** (e iperparametri) per scegliere il migliore. Restituisce un modello.',
    lesson: '04',
    section: 'I due obiettivi della validazione',
  },
  {
    id: 'model-assessment',
    term: 'Model assessment',
    def: 'Scelto il modello finale, stimarne l’errore di predizione su **nuovi dati di test**. Restituisce una stima.',
    lesson: '04',
    section: 'I due obiettivi della validazione',
  },
  {
    id: 'iperparametri',
    term: 'Iperparametri',
    def: 'Le scelte che definiscono il modello, come il grado $M$ del polinomio. Non sono i pesi trovati dal training: si fissano con la model selection.',
    lesson: '04',
    section: 'I due obiettivi della validazione',
  },
  {
    id: 'hold-out',
    term: 'Hold-out',
    def: 'Partizione del dataset in tre insiemi **disgiunti**: training set (TR), validation set (VL) e test set (TS).',
    lesson: '04',
    section: 'Hold-out',
  },
  {
    id: 'training-set',
    term: 'Training set',
    en: 'TR',
    def: 'Gli esempi usati per eseguire l’algoritmo di apprendimento.',
    lesson: '04',
    section: 'Hold-out',
  },
  {
    id: 'validation-set',
    term: 'Validation set',
    en: 'VL, selection set',
    def: 'Gli esempi usati per scegliere il modello migliore, ad esempio per regolare gli iperparametri.',
    lesson: '04',
    section: 'Hold-out',
  },
  {
    id: 'test-set',
    term: 'Test set',
    en: 'TS',
    def: 'Gli esempi usati **solo** per la model assessment: mai per scegliere o regolare $h$.',
    lesson: '04',
    section: 'Hold-out',
  },
  {
    id: 'k-fold',
    term: 'K-fold cross-validation',
    def: 'Si divide il dataset in $k$ parti disgiunte; a turno ognuna fa da validazione e le altre da training; si combinano i $k$ risultati.',
    lesson: '04',
    section: 'K-fold cross-validation (anticipazione)',
  },
  {
    id: 'matrice-di-confusione',
    term: 'Matrice di confusione',
    def: 'Tabella che incrocia classe reale e classe predetta: veri positivi (TP), falsi negativi (FN), falsi positivi (FP), veri negativi (TN).',
    lesson: '04',
    section: 'Matrice di confusione',
  },
  {
    id: 'accuratezza',
    term: 'Accuratezza',
    def: '$(TP+TN)/\\text{totale}$: la percentuale di pattern classificati correttamente. Con dati sbilanciati può essere fuorviante.',
    lesson: '04',
    section: 'Matrice di confusione',
  },
  {
    id: 'sensibilita',
    term: 'Sensibilità',
    en: 'recall, TP rate',
    def: '$TP/(TP+FN)$: quanti dei positivi veri vengono riconosciuti.',
    lesson: '04',
    section: 'Matrice di confusione',
  },
  {
    id: 'specificita',
    term: 'Specificità',
    en: 'TN rate',
    def: '$TN/(FP+TN)=1-FPR$: quanti dei negativi veri vengono riconosciuti.',
    lesson: '04',
    section: 'Matrice di confusione',
  },
  {
    id: 'precisione',
    term: 'Precisione',
    def: '$TP/(TP+FP)$: quanti dei predetti positivi sono davvero positivi.',
    lesson: '04',
    section: 'Matrice di confusione',
  },
  {
    id: 'curva-roc',
    term: 'Curva ROC',
    def: 'Il TP rate in funzione dell’FP rate al variare della soglia di decisione. La diagonale è il classificatore casuale; l’area sottesa (AUC) vale 1 per quello ideale.',
    lesson: '04',
    section: 'Curva ROC',
  },
]

export const glossaryById = new Map(glossary.map((g) => [g.id, g]))
